# Splitting the data into train and test sets.

## Before moving ahead to preprocessing stage, We separate the data into train and test sets mainly to prevent data leakage.

### Here we are splitting the data using the reference of 'Churn'. Because we need to ensure that each and every value of 'Churn' is equally distributed into train and test sets. Hence we use 'StratifiedShuffleSplit' method.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_customer_churn_data.csv")

In [3]:
df

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
440827,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440828,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440829,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440830,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440831,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

In [8]:
# StratifiedShuffleSplit
from sklearn.model_selection import StratifiedShuffleSplit

In [9]:
split = StratifiedShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

In [10]:
for train_index, test_index in split.split(df, df['Churn']):
    strat_train_set = df.iloc[train_index]
    strat_test_set = df.iloc[test_index]

In [11]:
strat_train_set

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
318330,42.0,Male,46.0,30.0,3.0,4.0,Standard,Annual,945.08,8.0,0.0
429061,33.0,Female,43.0,17.0,1.0,15.0,Standard,Annual,987.79,12.0,0.0
60074,26.0,Female,13.0,30.0,4.0,12.0,Premium,Quarterly,800.00,5.0,1.0
12759,29.0,Female,9.0,23.0,10.0,24.0,Basic,Quarterly,119.00,19.0,1.0
357320,38.0,Male,10.0,20.0,0.0,0.0,Basic,Annual,678.97,18.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
154141,46.0,Female,2.0,9.0,5.0,26.0,Premium,Annual,747.00,8.0,1.0
39618,22.0,Female,7.0,5.0,6.0,1.0,Basic,Quarterly,833.00,5.0,1.0
395142,47.0,Male,43.0,14.0,1.0,7.0,Basic,Annual,754.05,9.0,0.0
116290,34.0,Female,2.0,9.0,3.0,30.0,Basic,Quarterly,167.00,28.0,1.0
70108,52.0,Male,11.0,27.0,5.0,12.0,Premium,Monthly,711.00,25.0,1.0

In [12]:
strat_test_set

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
30086,62.0,Female,49.0,20.0,0.0,19.0,Basic,Monthly,175.00,22.0,1.0
368224,29.0,Male,32.0,27.0,2.0,2.0,Standard,Quarterly,733.00,25.0,0.0
146939,40.0,Female,39.0,16.0,8.0,0.0,Basic,Quarterly,542.00,3.0,1.0
368275,23.0,Female,13.0,28.0,0.0,11.0,Basic,Quarterly,951.67,1.0,0.0
153765,18.0,Male,10.0,15.0,3.0,15.0,Standard,Quarterly,970.00,17.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
170911,42.0,Female,5.0,27.0,3.0,3.0,Premium,Monthly,859.00,30.0,1.0
286321,34.0,Male,40.0,20.0,0.0,18.0,Basic,Annual,976.91,14.0,0.0
399597,26.0,Male,14.0,22.0,0.0,12.0,Standard,Annual,807.56,12.0,0.0
419237,43.0,Male,4.0,12.0,3.0,12.0,Standard,Annual,655.50,23.0,0.0
285859,29.0,Female,23.0,13.0,2.0,13.0,Premium,Quarterly,851.07,1.0,0.0

In [13]:
# Saving the training and testing data into two different csv files.
strat_train_set.to_csv("training_data.csv", index=False)
strat_test_set.to_csv("testing_data.csv", index=False)
print("Files saved successfully")

Files saved successfully